### ISSUE TITLE
MVP ML model

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#1]
## Detailed Description
Create a very simple model that 
- loads MVP data
- Splits data in GSP
- Use NWP solar irradiance to forecast GSP
- Save to database

<img width="285" alt="Screenshot 2022-01-13 at 20 27 12" src="https://user-images.githubusercontent.com/34686298/149404179-9e7a3ba6-7c4f-4b49-89b0-e87e1c0325f7.png">

## Context
very simple model for MVP, to get MVP working. This will later be swapped out with more complicated ML model
- Probably move this to its own github REPO
Useful for [nowcasting project](https://user-images.githubusercontent.com/34686298/148942185-e43e7183-bc61-4854-8f69-804036498625.png)

# Major tasks

- Save as netcdf: https://github.com/openclimatefix/MetOfficeDataHub/issues/12
- Manager live: https://github.com/openclimatefix/nowcasting_dataset/issues/575, which might involve adjusting how the NWP are saved in s3
- Load NWP netcdf: https://github.com/openclimatefix/nowcasting_dataset/issues/578
- simple NWP model: https://github.com/openclimatefix/nowcasting_forecast/issues/9
- run: https://github.com/openclimatefix/nowcasting_forecast/issues/8

# Minor tasks
- https://github.com/openclimatefix/nowcasting_dataset/issues/582
- https://github.com/openclimatefix/nowcasting_forecast/issues/11
- openclimatefix/nowcasting_api#67
- https://github.com/openclimatefix/nowcasting_api/issues/57
- https://github.com/openclimatefix/nowcasting_forecast/issues/14
- https://github.com/openclimatefix/nowcasting_forecast/issues/17
- https://github.com/openclimatefix/nowcasting_forecast/issues/13

**Comment by peterdudfield** [comment]
notes from chat

1. Use the same ‘Intermediate files’ if possible
2. Write `manager_live.py` in nowcasting_dataset to make live batches

**Comment by JackKelly** [comment]
on point 1., now that @jacobbieker has figured out how to download tiny files from EUMETSAT (~700 kB), I'd advocate for loading directly from those EUMETSAT NetCDF files (rather than going via a Zarr intermediate). Just to minimise the number of steps! It should be really fast to load images from 700 kB NetCDF files.

**Comment by jacobbieker** [comment]
Yeah, I'd go with using the netcdf files too, the one thing we need to check is if the data is calibrated or not, as Satpy does calibrate the native files.

**Comment by peterdudfield** [comment]
Thanks, for this MVP I'm just going to load NWP files. I'm still thinking to put the NWP into a zarr, (or netcdf file) and then load this

But for the future, that is super good to know that the satellite files are small. Would you have an example of one of these anyway?

**Comment by peterdudfield** [comment]
Tasks:

- Manager live: https://github.com/openclimatefix/nowcasting_dataset/issues/575, which might involve adjusting how the NWP are saved in s3
- simple NWP model: https://github.com/openclimatefix/nowcasting_forecast/issues/9
- run: https://github.com/openclimatefix/nowcasting_forecast/issues/8

**Comment by peterdudfield** [comment]
Main tasks are done, so ill close for now
