### ISSUE TITLE
Forecast looks 1 hour infront

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#106]
<img width="614" alt="Screenshot 2022-05-23 at 16 44 14" src="https://user-images.githubusercontent.com/34686298/169857249-55817cdd-0de4-42cc-b81a-057ebdf7cf68.png">

Looks like the forecast is one hour infront. 

Is this a timezone issue?

All internal datetimes are UTC, so need to check the datasources for live and for training are in the correct timezone

Checks
 - [x] Check Live PV data is in UTC
 - [x] Check traning PV data is in UTC
 - [x] Check NWP live data is UTC, and we havent converted it from BST to UTC
 - [x] Check live NWP is in correct timezone (UTC)
 - [x] Check model config for nwp is the same for training and live
 - [x] Check same NWP datetimes is given to training and live
 - [x] live satellite data looks right, it goes dark around 20.00 UTC
 - [x] CHeck training future GSP data
 - [ ] Does the live forecast need to use _floor(now), could it use

**Comment by peterdudfield** [comment]
PV data looks correct, as in this was taken at 15.48  UTC
<img width="715" alt="Screenshot 2022-05-23 at 16 47 53" src="https://user-images.githubusercontent.com/34686298/169857915-80fde19f-f74b-4d3d-babb-7c0281c05a7d.png">

**Comment by peterdudfield** [comment]
1. 
If the NWP data was in BST not UTC, then 
- Lets says the sun rise is 05.00 UTC, This is 06.00 BST
- Then our forecasts should start going up at 06.00 and the value from PV live would be at 05.00

2.
If the NWP data was in UTC, but we convert it from BST to UTC
- Lets says the sun rise is 05.00 UTC, This is 06.00 BST
- Data would have sunrise at 05.00 UTC, but we think it is BST, so we convert it to 04.00, 
- This soulw mean our forecasts would start going up at 04.00
Worth checking code for this

**Comment by peterdudfield** [comment]
For NWP, at 18.15, the init_time or model time is 14.00. This seems a bit late? I thought we would have more times by now from this

**Comment by peterdudfield** [comment]
NWP live data looks right, dswrf goes to zero around 20.00 UTC which is sunset today

**Comment by peterdudfield** [comment]
Model [hyper parametes ](https://app.neptune.ai/o/OpenClimateFix/org/predict-pv-yield/e/PRED-1001/all?path=hyperparams%2Fmodel%2F )are 
forecast minutes = 120
history minutes = 30
<img width="539" alt="Screenshot 2022-05-23 at 20 59 27" src="https://user-images.githubusercontent.com/34686298/169896625-940f84f1-3e5a-465a-9d93-89402e740264.png">

but gcp configuration file is
forecast minutes = 120
history minutes = 60

V2 forecast config is
history minutes 60, 
forecast minutes 120
<img width="368" alt="Screenshot 2022-05-23 at 21 02 15" src="https://user-images.githubusercontent.com/34686298/169897060-b7f1a462-a158-4f0a-af9a-88701e04451c.png">

**Comment by peterdudfield** [comment]
Looking at NWP live batch made at 20.57 BST (19.57 UTC)
The datetimes are
- 18:00
- 19:00
- 20:00
- 21:00

I think this is right

Looking at a training batcht
with t0=09:15
- 08:00
- 09:00
- 10:00
- 11:00

Live and trainin match

**Comment by peterdudfield** [comment]
Look into why timzone is Eureop/London - https://github.com/openclimatefix/PVConsumer

**Comment by peterdudfield** [comment]
Live PV data might be off
<img width="702" alt="Screenshot 2022-05-23 at 22 03 34" src="https://user-images.githubusercontent.com/34686298/169905801-a7ced7ce-ac8c-4a0b-b76a-9ab59b656bbe.png">
<img width="941" alt="Screenshot 2022-05-23 at 22 03 45" src="https://user-images.githubusercontent.com/34686298/169905808-ba3e4a31-4cfc-4ef5-93d2-3f7f678353f2.png">

**Comment by peterdudfield** [comment]
<img width="589" alt="Screenshot 2022-05-23 at 22 06 09" src="https://user-images.githubusercontent.com/34686298/169906050-6838e169-caf2-4c5b-a448-522315256ac6.png">
Althought it does say the systems are in Europe/London

**Comment by JackKelly** [comment]
Eye balling the chart, is it possible the forecast is behind by 30 mins (not 1 hour)? So maybe it's an issue with the rounding down?
