### ISSUE TITLE
Solar forecast consistly over estimates

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#114]
Over the last few days, solar forecast seems to be constantly over forecasting

One clue could be 
- plot all MAE's per GSP and see if an stick out?
- seems to be large errors around Sheffield? Is there a funny PV system here

**Comment by peterdudfield** [comment]
<img width="1338" alt="Screenshot 2022-05-30 at 12 41 07" src="https://user-images.githubusercontent.com/34686298/170985033-8eedb7dd-504f-43f2-9d4d-0ee976754394.png">

MAE over last day per GSP

**Comment by peterdudfield** [comment]
![Uploading Screenshot 2022-05-30 at 12.48.01.png…]()

Also Keadby seems to at zero, for a long time

**Comment by peterdudfield** [comment]
<img width="774" alt="Screenshot 2022-05-30 at 13 44 24" src="https://user-images.githubusercontent.com/34686298/170995040-1030f754-186f-45f0-83d9-54c8ae1b6099.png">

There system have pv yields over 100%. 

Actions: 34165 reduce capacity

**Comment by peterdudfield** [comment]
[24565](https://pvoutput.org/intraday.jsp?id=24565&sid=24565&dt=20220530) - 4kwp
[42795](https://pvoutput.org/intraday.jsp?id=42795&sid=42795&dt=20220530) - 4
[49643](https://pvoutput.org/intraday.jsp?id=49643&sid=49643&dt=20220530) - 3.5
[67123](https://pvoutput.org/intraday.jsp?id=67123&sid=67123&dt=20220530) - 
[63689](https://pvoutput.org/intraday.jsp?id=63689&sid=63689&dt=20220530) - 

Other systems that might need checking
[58944](https://pvoutput.org/intraday.jsp?id=58944&sid=58944&dt=20220530) - 3
[47944](https://pvoutput.org/intraday.jsp?id=47944&sid=47944&dt=20220530)
[41651](https://pvoutput.org/intraday.jsp?id=41651&sid=41651&dt=20220530)
[31970](https://pvoutput.org/intraday.jsp?id=31970&sid=31970&dt=20220530)
[21570](https://pvoutput.org/intraday.jsp?id=21570&sid=21570&dt=20220530)
[13551](https://pvoutput.org/intraday.jsp?id=31970&sid=13551&dt=20220530)

**Comment by peterdudfield** [comment]
sql
```
select DISTINCT on (pv_system.pv_system_id) solar_generation_kw,installed_capacity_kw,pv_system.pv_system_id,  * from pv_yield
join pv_system on pv_yield.pv_system_id = pv_system.id
where datetime_utc > '2022-05-22'
and solar_generation_kw > installed_capacity_kw * 1.05
```

**Comment by peterdudfield** [comment]
Decided to update them all to be max values

**Comment by peterdudfield** [comment]
<img width="676" alt="Screenshot 2022-05-31 at 11 30 01" src="https://user-images.githubusercontent.com/34686298/171153697-1ac559da-6e12-4597-ac77-7c89615496cb.png">
Looks slightly better today, but not totally

**Comment by peterdudfield** [comment]
Some plotting errors on main app - https://github.com/openclimatefix/nowcasting/issues/62

**Comment by peterdudfield** [comment]
Looking at v15 data 0 batch, 0 example, we t0=09.15 and gsp times are:
array(['2021-08-06T07:00:00.000000000', '2021-08-06T07:30:00.000000000',
       '2021-08-06T08:00:00.000000000', '2021-08-06T08:30:00.000000000',
       '2021-08-06T09:00:00.000000000', '2021-08-06T09:30:00.000000000',
       '2021-08-06T10:00:00.000000000', '2021-08-06T10:30:00.000000000',
       '2021-08-06T11:00:00.000000000', '2021-08-06T11:30:00.000000000',
       '2021-08-06T12:00:00.000000000', '2021-08-06T12:30:00.000000000',
       '2021-08-06T13:00:00.000000000', '2021-08-06T13:30:00.000000000',
       '2021-08-06T14:00:00.000000000', '2021-08-06T14:30:00.000000000',
       '2021-08-06T15:00:00.000000000', '2021-08-06T15:30:00.000000000',
       '2021-08-06T16:00:00.000000000', '2021-08-06T16:30:00.000000000',
       '2021-08-06T17:00:00.000000000'], dtype='datetime64[ns]')

1st target time is 09.30

when looking at live we see
t0=20.00 and gso datetime sare
array(['2022-05-31T18:30:00.000000000', '2022-05-31T19:00:00.000000000',
       '2022-05-31T19:30:00.000000000', '2022-05-31T20:00:00.000000000',
       '2022-05-31T20:30:00.000000000'], dtype='datetime64[ns]')

1st target time is 20.30

So ....
Note in training t0 ahead of 5th data point by 15mins, but in live, t0 is equal of 5t datapoint by 30 mins. 
In live we should load data from 18:00 to 20:00. This mistake woulc cause an over predictoin in the morning and underprediction in the afternoon.

**Comment by peterdudfield** [comment]
deployed in 1.1.3

**Comment by peterdudfield** [comment]
AT 7.20 UTC the PV dataset times are
<xarray.DataArray 'time' (time_index: 7)>
array(['2022-06-01T06:50:00.000000000', '2022-06-01T06:55:00.000000000',
       '2022-06-01T07:00:00.000000000', '2022-06-01T07:05:00.000000000',
       '2022-06-01T07:10:00.000000000', '2022-06-01T07:15:00.000000000',
       '2022-06-01T07:20:00.000000000'], dtype='datetime64[ns]')
Coordinates:
    example     int32 0
  * time_index  (time_index) int32 0 1 2 3 4 5 6
  
For training
to for 9.15
array(['2021-08-06T08:45:00.000000000', '2021-08-06T08:50:00.000000000',
       '2021-08-06T08:55:00.000000000', '2021-08-06T09:00:00.000000000',
       '2021-08-06T09:05:00.000000000', '2021-08-06T09:10:00.000000000',
       '2021-08-06T09:15:00.000000000', '2021-08-06T09:20:00.000000000',
       '2021-08-06T09:25:00.000000000', '2021-08-06T09:30:00.000000000',
       '2021-08-06T09:35:00.000000000', '2021-08-06T09:40:00.000000000',
       '2021-08-06T09:45:00.000000000', '2021-08-06T09:50:00.000000000',
       '2021-08-06T09:55:00.000000000', '2021-08-06T10:00:00.000000000',

This look about right. 
The only difference would be in live t0 is 7.00, so we would expect data from 6.30 to 7.00

**Comment by peterdudfield** [comment]
PV system id 41651 has the wrong capacity, changing it to 6kW

**Comment by JackKelly** [comment]
ah, yes, I would totally ignore the "nominal" capacity. Instead, I think we should use the max power of the complete history for that PV system (i.e. using multiple years of history that we downloaded for ML training). And, of course, we definitely need to use the same "capacity" per PV system at inference time as at training time :slightly_smiling_face:

**Comment by JackKelly** [comment]
I'm really sorry but please could you outline again why the fix is to interpolate the GSP data? (Any additional data processing like interpolation always makes be a bit nervous!)

**Comment by peterdudfield** [comment]
Well, we have a choice, are currently model assuems the last GSP datestamp is there. 

E.g. at 9.05, it assumes that 9.00 GSP is there. However it is not available yet. At 9.15, the data will be available. 

On balance I think here, its better to interpolate, rather than use less data. (in this situation)

**Comment by jacobbieker** [comment]
If there is a delay, could we do what we do for satellite, and have a model that is trained on only the ones that would be available? I don't know how long it takes to retrain the CNN, but that might then get rid of the need to interpolate

**Comment by peterdudfield** [comment]
> If there is a delay, could we do what we do for satellite, and have a model that is trained on only the ones that would be available? I don't know how long it takes to retrain the CNN, but that might then get rid of the need to interpolate

it takes a few hours to retrain so thats not a problem

Its tricky, becasue the data does become available during that 30 mins, and we should use that data for the next predictions. 
We could
- one model if data isnt avialable
- model if data is available
- logic to decide which model to run

Above is quite complicated, hence, I think a bit of interpolating keeps things simplier here

**Comment by peterdudfield** [comment]
> Yeah, that makes sense! If we are planning on having these fallback models incase certain data is not available, which I think was the plan? then it might be good to build it starting for this? It might have to wait till after WP2 is done, but it would be good to have fallback models, especially since we know satellite data will change for at least 2 days each month

yea definately for Wp3, we should have a non satellite model

**Comment by peterdudfield** [comment]
> > Yeah, that makes sense! If we are planning on having these fallback models incase certain data is not available, which I think was the plan? then it might be good to build it starting for this? It might have to wait till after WP2 is done, but it would be good to have fallback models, especially since we know satellite data will change for at least 2 days each month
> 
> yea definately for Wp3, we should have a non satellite model

Unless the 15 mins satellte data is good enough?

**Comment by jacobbieker** [comment]
The 15 minutely data is the same as the 5 minutely one, so the data will be the same, but it will have a different temporal frequency, which I would think would mess up the CNN trained on 5 minutely

**Comment by peterdudfield** [comment]
> The 15 minutely data is the same as the 5 minutely one, so the data will be the same, but it will have a different temporal frequency, which I would think would mess up the CNN trained on 5 minutely

is it exactly the same? Like same values for each pixel? 

As a quick one liner fix: We could interpolate to 5 minutely and then CNN would work

**Comment by peterdudfield** [comment]
> Yeah, it's exactly the same, same sensor, same readout, same values, just the whole rensor being read instead of a section of it for the 5 minutely one.

great stuff,  ill put it on assana and we can work out how to use it best

**Comment by peterdudfield** [comment]
> > Yeah, it's exactly the same, same sensor, same readout, same values, just the whole rensor being read instead of a section of it for the 5 minutely one.
> 
> great stuff, ill put it on assana and we can work out how to use it best

https://app.asana.com/0/1201681902047911/1202419451952429

**Comment by peterdudfield** [comment]
No longer consisting over predictin. Removed some systems that were not in the correct timezone

**Comment by JackKelly** [comment]
I'd guess we'd want to use optical flow to upsample 15-minute satellite
imagery to 5-minutely. Just interpolating the pixel values would, I'd
guess, result in blurry images. But maybe the CNN won't care!

On the topic of interpolating GSP PV power values: I agree that
interpolating sounds like the right choice to the CNN.

For OptiFlow v2, it should "naturally" be able to cope with PV, GSP, and
satellite imagery arriving at slightly different times, without any need to
interpolate or fill. (That's the hope, anyway!) It's trained with PV data
arriving at any 5-minute interval past the hour (so, for 5/6th of the
training examples, the PV data is out-of-step with the GSP data), and that
seems to work OK.

(My current plan is, next week, to write code to load data directly from
the "intermediate" representations in the production system, so hopefully
the optiflow v2 model can have its own custom data loader, skipping
interpolation. In WP3 we can figure out how best to reduce duplication in
the data loading code for different models, whilst still allowing different
models to slice and pre-process the data differently :) )
