### ISSUE TITLE
Strange PV data

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#117]
Some PV systems have odd data 
It may be better to remove some of these,
or we could still collect the data but not add them to the forecast

For example system 37543

<img width="696" alt="Screenshot 2022-06-07 at 21 51 58" src="https://user-images.githubusercontent.com/34686298/172480243-5bf89cfd-afa7-4e29-87b5-2068d46f3021.png">

Full list
ODD
- 20471: odd results - also in pvoutput.org - now looks ok
- 30248: lots of zeros - Manchester - error - should remove - correct_data=False
- 37543: not zero in the night - Scotland - correct_data=False
- 38254: constant non zero value - Near Luton. Issue only started on 06-06-2022 - correct_data=False
- 40283: lots of zeros - Reading - Looks fine, our installed capacity might be too big. It should be 4 kW - already at 3.6 - https://github.com/openclimatefix/PVConsumer/issues/29

Capacity issue
- 2490: close to zero - Manchester - Looks fine, our installed capacity might be too big. It should be 3.43 kW - Updated
- 5257: close to zero - Hastings - Looks fine, our installed capacity might be too big. It should be 3.92 kW - Updated
- 27003: close to zeros - London - Looks fine, our installed capacity might be too big. It should be 2.1 kW - Updated 
- 42586: lots of zeros - Ireland - Looks fine, our installed capacity might be too big. It should be 4 kW - updated
- 44135: lots of zeros - Ireland - Looks fine, our installed capacity might be too big. It should be 2 kW, already at 2.152
- 57569: always zero - Ipswich - Looks fine, our installed capacity might be too big. It should be 2.95 kW, already set at 2.26
- Also updated 5729

Alternating zeros
- 6964: alternating zeros - no zeros in pvoutput.org. Might be a bug in PVConsumer - also see these in the database
- 45118: alternating zeros - Eastbourne - no zeros in pvoutput.org. Might be a bug in PVConsumer
- 51657: alternating zeros - Seven oaks - no zeros in pvoutput.org. Might be a bug in PVConsumer
- 61764: alternating zeros - Wales - no zeros in pvoutput.org. Might be a bug in PVConsumer
Moved this to https://github.com/openclimatefix/PVConsumer/issues/26

Think it would be good to have two modifications in in the datamodel
1. add column, defect: boolean. We can then only load when defect=True
2. Add column that describes what post processing the PV data should have. This can be done when loading the data. Its good to save the raw data. We obviously dont want to do to much post processing, but we should use domain knowledge to adjust obvious errors

**Comment by peterdudfield** [comment]
61764 - seems to have lots of zeros in it
<img width="686" alt="Screenshot 2022-06-07 at 21 53 18" src="https://user-images.githubusercontent.com/34686298/172480488-3a4c0d4f-02ea-4a6a-b126-62ef3dae381e.png">

**Comment by peterdudfield** [comment]
20471
<img width="716" alt="Screenshot 2022-06-07 at 21 54 30" src="https://user-images.githubusercontent.com/34686298/172480732-93faf51a-c03a-4cd7-9dbb-09f4cc390bf7.png">

**Comment by peterdudfield** [comment]
57569 - always zero


<img width="729" alt="Screenshot 2022-06-07 at 21 55 03" src="https://user-images.githubusercontent.com/34686298/172480841-a0c62aa1-34cc-415b-9f68-7077e1a654b3.png">

**Comment by peterdudfield** [comment]
5257 - close to zero
<img width="696" alt="Screenshot 2022-06-07 at 21 55 38" src="https://user-images.githubusercontent.com/34686298/172480924-fad912e8-dda2-4580-a8f4-c0e23bba80f6.png">

**Comment by peterdudfield** [comment]
44135 - lots of zeros

<img width="717" alt="Screenshot 2022-06-07 at 21 56 36" src="https://user-images.githubusercontent.com/34686298/172481151-361a9306-1f52-4cce-ac13-af031eab1b3c.png">

**Comment by peterdudfield** [comment]
A lot of zeros was solved by a incorrect installed capacity, so it looked like zero but was not. 

Yea, we set the installed capacity by the maximum power (from training data), we could update these with the installed capacity from pv outputorg, but I thought this number was less reliable.

**Comment by peterdudfield** [comment]
Alos set 13764 to inccoect data as not zero in the night

**Comment by JackKelly** [comment]
> Yea, we set the installed capacity by the maximum power (from training data), we could update these with the installed capacity from pv outputorg, but I thought this number was less reliable.

Yeah, exactly. I'd ignore the capacity from pvoutput.org, and just use the max over the entire timeseries (assuming we have at least, say, 6 months of data).

**Comment by peterdudfield** [comment]
can close this for the moment
