### ISSUE TITLE
Get Power Perceiver working on fake batch (BatchML)

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#118]
Get Power Perceiver working on current batch format

The most recent batch is save [here](https://s3.console.aws.amazon.com/s3/buckets/nowcasting-ml-models-development?region=eu-west-1&prefix=batch/&showversions=false)

You can load it using the method from nowcasting_dataloader - 
https://github.com/openclimatefix/nowcasting_dataloader/blob/main/nowcasting_dataloader/datasets.py#L186
```
from nowcasting_dataset.dataset.batch import Batch

batch = Batch.download_batch_and_load_batch(
                    batch_idx=batch_idx,
                    data_sources_names=['gsp','pv','nwp'],
                    tmp_path='./temp,
                    src_path='s3://nowcasting-ml-models-development/batch/',
                )
```

or you can use make a configruation and run
```
batch = Batch.fake(configuration)
```

**Comment by JackKelly** [comment]
I'm imagining using the existing `nowcasting_forecast` code to generate `BatchML` objects, and then I'll write a simple wrapper to convert `BatchML` into [the structure that Helios expects](https://github.com/openclimatefix/power_perceiver/blob/main/power_perceiver/consts.py#L25).

**Comment by JackKelly** [comment]
See this example of how the existing CNN model gets the dataloader: https://github.com/openclimatefix/nowcasting_forecast/blob/main/nowcasting_forecast/models/cnn/dataloader.py

**Comment by peterdudfield** [comment]
Not needed any more, as we are using ocf_datapipes
