### ISSUE TITLE
Investigate gap in forecast

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#122]
2020-06-15th the forecast didnt seem to run in the night? 
why?

<img width="591" alt="Screenshot 2022-06-16 at 07 52 08" src="https://user-images.githubusercontent.com/34686298/174009730-fb581048-383e-4651-a910-b316af871b80.png">

**Comment by peterdudfield** [comment]
**Backfill**
We do not have the ability to backfill right now. The process is defined quite specifically to be data efficient and not do that. 
Perhaps something for WP3, need to work out how much we need it

**Pv night**
Yea, I agree, perhaps some nights it just reaches over (so there is no gap in the yellow line), but yea I assume to this is the case. 

Solutions
1. Passiv data gives 0's in the night which is nice, so by adding passiv data the forecast could be find. This seems a bit risky and other things might need fixing. Like 
2. Add 0's to pv data, if elevation < 0. This seems a bit dodgy as we are adding data that is not there. Although it does seem a safe edit.
3. When loading pv data to nowcastin_dataset, if with elevation<0, then add some zeros. This should help smooth it over

My hunch is to go for 3. What do you think @JackKelly ?

**Comment by peterdudfield** [comment]
**PV at night**

Perhaps we can do below -10, to be sure. But it feels right even to do 0

Thats good that in the near future PP can support that. Thats good. 


**Broken forecast on 15th and 29th June**
It looks like it does happen every night. 

Here's a image of the error. Something to do with size of things. 
Perhaps this a quick fix, and we dont need to start adding zeros. Ill have to look at it further
<img width="1104" alt="Screenshot 2022-06-29 at 12 16 39" src="https://user-images.githubusercontent.com/34686298/176424055-422e1580-99b7-4780-acbf-df053965c5d9.png">

**Comment by peterdudfield** [comment]
Looking at the batch file in s3 from now. The shape is 
torch.Size([32, 7, 128]). Note 7*128 =896. So need to look at nowcast_dataset code, and see how it handles when there is no data.

**Comment by peterdudfield** [comment]
Looks like essentially an empty dataframe is returned - https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/pv/live.py#L129

Should be able to add some NaNs in here

**Comment by peterdudfield** [comment]
Solution for this has been deployed. Well have to look tomorrow if this is sorted

**Comment by JackKelly** [comment]
Great work! Fingers crossed!

**Comment by peterdudfield** [comment]
Unfortunately this solution didnt work, but a Forecast was made between 03:30 to 04:00. UK time. 
Need to look further into why it didnt work around 03:30, the bug seemed to be the same as the screen shot above

**Comment by JackKelly** [comment]
Would it help us to diagnose the issue if we added some more data validation (specifically checking that things are the right shape?)

**Comment by peterdudfield** [comment]
Im just adding some logging to the and hope to do a bit more filling, then should be ok

**Comment by peterdudfield** [comment]
New forecast has been deployed, lets check the logs this evening, to see if the model ran (even though the different issue will mean no forecasts are saved)

**Comment by peterdudfield** [comment]
WIll close this for the moment
