### ISSUE TITLE
Large forecast error

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#123]
<img width="1322" alt="Screenshot 2022-06-20 at 12 32 06" src="https://user-images.githubusercontent.com/34686298/174592846-e030ac45-1bbc-4c71-9afd-0abb77b0f976.png">

Around 11.30 UTC time, we see large error around Manchester

I suspect this is an odd PV system

**Comment by peterdudfield** [comment]
```
select * from pv_yield
join pv_system on pv_system.id = pv_yield.pv_system_id
where datetime_utc>'2022-06-20'
and pv_yield.solar_generation_kw > pv_system.installed_capacity_kw
```

System ids with problems are 
20353
41651

**Comment by peterdudfield** [comment]
Need to update installed capacity to 1.975kW

**Comment by peterdudfield** [comment]
https://pvoutput.org/intraday.jsp?id=20353&sid=20353&dt=20220619&gs=0&m=1

**Comment by peterdudfield** [comment]
Done this on both dev and production

**Comment by dantravers** [comment]
Could this happen again in the future if a new system comes online?

**Comment by peterdudfield** [comment]
> Could this happen again in the future if a new system comes online?

yea, but low probably. It has to be in our selected PV systems that we have used to train. Some of these are offline now, compared to training data. 

I think we should access again, if that happens again
