### ISSUE TITLE
Forecast memory

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#127]
When loading 15 minutely satellite data, the forecast runs out of memory. 

We could up the memory, but would prefer to tackle why the satellite data is different

**Comment by jacobbieker** [comment]
How much memory does the interpolation use? That might cause a bigger bump than just loading the outputs from the RSS. Might need to do the interpolation in Satip if that's the case

**Comment by peterdudfield** [comment]
I'll add some logging, thats a good point though
