### ISSUE TITLE
Expand elevation limit

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#134]
We currently limit forecast when elevation <0. Could we move this up to 5? 

This might get rid of the bump we are seeing at the moment
<img width="610" alt="Screenshot 2022-06-30 at 12 03 32" src="https://user-images.githubusercontent.com/34686298/176661994-1e302012-23b8-46a9-8328-83e65181fd8f.png">

Idea is to plot 10 GSP on 10 different days and check

**Comment by JackKelly** [comment]
> Could we move this up to 5?

SGTM!

**Comment by JackKelly** [comment]
Should we discuss this "bump" in the WP2 report, in the section on "limitations"? It might be good to flag up this "bump" to our users?

**Comment by peterdudfield** [comment]
@JackKelly best to @kasiaocf and @dantravers on Slack maybe

**Comment by peterdudfield** [comment]
Thanks @jacobbieker for your work on this

**Comment by peterdudfield** [comment]
![2019-02-28 00_00_00](https://user-images.githubusercontent.com/34686298/176727441-7fe477a5-4c8f-454f-8eb6-1f6e8bc4b816.png)
