### ISSUE TITLE
Check night forecast is ok

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#135]
OCF humans currently have not visibility of early morning forecast, lets plot these and check they are ok

BONUS: would be good to add a script that plot these for any time

**Comment by peterdudfield** [comment]
<img width="1379" alt="Screenshot 2022-06-30 at 12 40 26" src="https://user-images.githubusercontent.com/34686298/176668754-9798fd4b-c5d8-4f81-a53c-d7f6ef206274.png">

Until we get to 05:30 in the morning, the forecasts dont look good.

**Comment by JackKelly** [comment]
Thanks for doing this analysis!

For now, maybe we just shouldn't produce any forecasts until, say, the Sun is 5 degrees above the horizon? For now, I'd rather publish nothing than publish something that's wrong :slightly_smiling_face:

**Comment by peterdudfield** [comment]
2. gets tricky as if one GSP forecast is not made, then a national on is no made either.

**Comment by jacobbieker** [comment]
For 2. Could we set the forecast for the gsp to 0, so then it can still run national but that gsp doesn't count?

**Comment by peterdudfield** [comment]
> For 2. Could we set the forecast for the gsp to 0, so then it can still run national but that gsp doesn't count?

This would potentially make the national forecast 50% of what it should be (which isn far off what we have now). 
I think it would have to be, if any GSP elevation now < Y, then dont save the forecast?

**Comment by JackKelly** [comment]
Would it help if we used a single elevation threshold for the entire country? (e.g. the "centroid" of GB)? That way, we'd know that we'd either have _all_ the GSPs, or we'd have _none_ of the GSPs. Which maybe helps ensure that we're always computing the national forecast with the full complement of GSPs?

**Comment by peterdudfield** [comment]
From discussion
- Use 2. use limit of 5 sun elevation (5 to be safe, can adjust later)
- Centroid will be oxford (PV weighted uk center)
- Also set status to warning, when no PV forecast is made. This then show up in UI (when ready)
