### ISSUE TITLE
National Forecast < Nataionl PV Live

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#150]
Following on from 
https://github.com/SheffieldSolar/PV_Live-API/issues/16
Our National Forecast is less than the PV Live Forecast. This is due to some GSP having Nans in them. 

I think we have a few different solutions
1. Use PVlive to calculate an average derivation from sum(GSPs) - National and add this to our national forecast. 
2. Re-train PVnet but add in some random GSP zeros in the data. So the model knows if GSP history is zero, it still gives a resonable outcome. This should make reasonable forecast for the GSPs with no data, and our nataionl forecast will therefore increase. 
3. Provide a model with fake GSP historic, by taking an average of the PV systems for that GSP. Then run PVnet normally. 

@jacobbieker what do you think (Let me know if you need more context)
![Screenshot 2022-07-27 at 17 00 48](https://user-images.githubusercontent.com/34686298/181294561-8ae64985-c8a1-47a4-b8f7-5412bf19b266.png)

**Comment by peterdudfield** [comment]
I think my preferred is 2.

**Comment by jacobbieker** [comment]
I think 2 is also my preferred, followed by 3. 2 seems the simplest and most straightforward.

**Comment by peterdudfield** [comment]
cool - ok, ill add something in to dataloader, than randomly takes gsp history data to zero. Seems about 10% of the UK capacity deos this, so Ill do 10% of the batches

**Comment by peterdudfield** [comment]
Got i training here - https://app.neptune.ai/o/OpenClimateFix/org/predict-pv-yield/e/PRED-1177/monitoring
10% of GSP history going to zero

**Comment by peterdudfield** [comment]
This is now no longer relevant
