### ISSUE TITLE
Option not to make batches

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#161]
have option in forecaster not to not to make batches - [here](https://github.com/openclimatefix/nowcasting_forecast/blob/main/nowcasting_forecast/app.py#L135)

have simple bool click command

tests:

try this command out, with CNN model and check it fails

**Comment by peterdudfield** [comment]
Do you mind doing this @jacobbieker ?

**Comment by jacobbieker** [comment]
Yep! Sounds good

**Comment by peterdudfield** [comment]
thanks
