### ISSUE TITLE
Missing 4-hour forecast on UI for a few hours

### ISSUE THREAD

**Issue by dantravers** [openclimatefix/nowcasting_forecast#174]
Just noticed this today (9/11/22, 15:24), and noticed that the Development UI has no data for the 4 hour behind forecast: 
![image](https://user-images.githubusercontent.com/38562875/200872283-4237553a-6ca7-4c3e-a844-b8f61d4de87d.png)

The Yellow (latest) forecast line however is there for all hours on Development. 

However on Production, there is no 4-hour forecast line, but the latest forecast line is missing from 8:00am and earlier - through the whole night in fact.  (It isn't missing on dev.) This might be related, but hard to say!
![image](https://user-images.githubusercontent.com/38562875/200873279-30a56941-5cc6-410f-bea1-3198a60c5732.png)

Note that teh Auth0 work was being implemented on dev today, if this could have inteferred in some way?

Further note that the Dev and Prod profiles are different.   Not sure why?

**Comment by peterdudfield** [comment]
I suspect dev and pro are different due to dev not running for a few hours, hence why there is a gap in the four hour forecast. Would have to check in the logs if this is true or not.

**Comment by rachel-labri-tipton** [comment]
this is from the array console logged on dev. there's the gap 10:30 - 13:00: ![Screenshot 2022-11-09 at 16 41 20](https://user-images.githubusercontent.com/86949265/200875128-cdcdacfe-a3cb-4afd-976d-9c33aa886da9.png)

**Comment by peterdudfield** [comment]
thanks yea, will have to look in AWS logs why the forecast didnt run at for example 8.00, which would make a 4 hour forecast for 12.00

**Comment by peterdudfield** [comment]
I saw this issue this morning on NWP consumer, this could be connected - [logs](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fconsumer$252Fnwp$252F/log-events/streaming$252Fnwp-consumer$252F138822a10a134a8ab93f53e626ba3f05)

![Screenshot 2022-11-17 at 08 03 47](https://user-images.githubusercontent.com/34686298/202390373-bf1bd91d-e37b-4d7d-8240-393131ab6473.png)
