### ISSUE TITLE
Save one batch to s3

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#59]
## Detailed Description
Would be good to save one batch to s3. This means we could analysis and do checks that the data going into the forecast model is correct

## Possible Implementation
Have option in make_batches to save first batch to a folder (which could be s3). Could also save all batches, if the size is not to big

**Comment by peterdudfield** [comment]
This could also been done in 'nowcasting_dataloader' so we know exactly what goes into the model

**Comment by peterdudfield** [comment]
Ive added a click argument, that can be used to say where to save the batches. 

Perhaps we could do
{path}/batch for #78 
{path/batchml for #121 (or equiv in this repo)

**Comment by jacobbieker** [comment]
Yeah, that sounds good to me! I'll add that to this repo for it
