### ISSUE TITLE
Load satellite live bug

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#68]
## Detailed Description
Need to adjust so that live satellite images can be loaded into batches. The problem is they are about ~20 mins behind, so probably need to the expected shape in 'nowcasting_dataset'

**Comment by peterdudfield** [comment]
Some other context

Satellite batches. When loading satellite batches from live, i think we might get an error, but the data will be the wrong shape. This is due to the satlellites images being ~20 mins behind. The model can deal with the data not being there, but nowcast_dataset will get upset becasue it expects it in a certain format. 

One way to solve this, could be to forward fill the data if live. Another way could be to adjust the expected shape if live. I think I prefer the expected shape method, as we dont fill in empty data

**Comment by peterdudfield** [comment]
Seems there is a little bug - says there are some nans in the satellite data. I wonder if this is data from northern scotalnd?

I thought padding had fixed this

**Comment by JackKelly** [comment]
This is an interesting issue!

For the MVP, I think I'd lean towards keeping life as simple as possible and defining `t0` as `the time of the most recent observation, across all modalities`. 

So, for example, let's say it's 12:00pm now. We have PV data up until 11:55am. But the satellite data is 30 minutes behind, so the most recent satellite image is from 11:30am. For now, I'd lean towards defining `t0` as 11:30am., e.g. we'd use  9:30am - 11:30am as the "history", and get the ML model to predict at least 2.5 hours into the "future", so the predictions span from 11:30am to 2pm.

In WP3, we can worry about how to deal with different input modalities being updated with different latencies (e.g. how do we always make use of 5-minutely PV data, even when the satellite data is 30 minutes late)?

One disadvantage of using a U-Net to predict the future satellite imagery is I'm really not sure how well the U-Net will cope if the input data has missing satellite timesteps. We could try training the U-Net with random satellite timesteps missing. But I'd propose that we don't do that in WP2.

**Comment by peterdudfield** [comment]
Hey @JackKelly 

we've already implented something for satellite data, which is to assume the last 30 mins is not available. I think we should see how this goes, and if it doesnt work, we can easily turn it off and got for your method
