### ISSUE TITLE
Strange results for CNN model

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#81]
When first running the model we get some odd results. Often the predictions are negative

```
select * from forecast
join forecast_value on forecast.id = forecast_value.forecast_id
join location on location_id = location.id
join model on model_id = model.id
where model.name  = 'cnn'
and gsp_id = 1
```

- [x] Save one batch to s3, so we can see what is going into the model
- [x] check same values are normalized in training and in inference, for sat and nwp
- [x] Notice PV data has very little data in it
- [ ] Investigate effect of little PV data
- [x] Check no difference between examples with PV data and examples without
- [x]  Sun is None in inference batch, is it in training? yes
- [ ] Run inference using one of the pre preapred batches using the model and check results are ok, v15
- [ ] Chekc Satellite compression is the same in training and inference
- [ ] Check for any Ints where they should be floats
- [ ] check tensor floats 32 / 64 is the same in training and inference
- [ ] plot satellite image in prediction and training batch, see if there is anything different
- [x] check model is loaded - https://github.com/openclimatefix/nowcasting_forecast/pull/82

<img width="850" alt="Screenshot 2022-05-17 at 15 05 34" src="https://user-images.githubusercontent.com/34686298/168830217-57fc0922-725a-4626-a3f7-029a9815b387.png">

- [ ] should we run the model in 'eval' mode
- [ ] does the model post processing mucking up the results? https://github.com/openclimatefix/nowcasting_forecast/pull/82 might help with this - [live logs](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fforecast$252F/log-events/streaming$252Fforecast$252F52cac29d068b47258465a84611c6c02c)
- [x] run model locally with batchml from s3. Check model results are reasonable. i.e non negative. If so post-processing could be mucking it up
            All model results are postive
- [ ] ...

**Comment by jacobbieker** [comment]
- [ ] Sun is None in inference batch, is it in training?

**Comment by peterdudfield** [comment]
We think we've sovled it

https://github.com/openclimatefix/nowcasting_forecast/blob/main/nowcasting_forecast/models/utils.py#L244

```
model.load_model(use_hf=use_hf).eval()
```
should be
```
model = model.load_model(use_hf=use_hf).eval()
```





[15:41](https://openclimatefix.slack.com/archives/D02A505NGMD/p1652798467451499)
should be
model = model.load_model(use_hf=use_hf).eval()
