### ISSUE TITLE
CNN satellite data, not enough

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#85]
Satellite data seems to be sometimes not working. Not enough data.

Did not work at 16.04
Worked at 16.24

**Comment by jacobbieker** [comment]
Some options for dealing with it:
Leaving the last n frames even if they are older in latest
Have a backup to the 15 minutely satellite data that is also available for when the RSS is shut off or unavailable

**Comment by peterdudfield** [comment]
Did work at 16.51 and 16.56
Didn't work at 17.01, 
Did work at 17.06

**Comment by JackKelly** [comment]
> the number of timesteps in the latest zarrs changes if the satellite data isn't available on time, so it'll fluctuate between 11 and 13 I think

that'll def be a prob for the u-net. Is there a way to guarantee there are always an exact number of consecutive timesteps available? even if that means delaying t0 a bit?

**Comment by peterdudfield** [comment]
yea, I think a way to do it is to always trim down to 11 or always trim down to the minimum. Admittedly this does mean some data is lost. 

The way its written is t0 is constant in 30 mins blocks, might be a bit harder to make t0 more flexible

**Comment by JackKelly** [comment]
> I think a way to do it is to always trim down to 11 or always trim down to the minimum. Admittedly this does mean some data is lost.

For the MVP, I'd agree that it's probably best to do whatever it takes to have a reliable service, even if that slightly hurts performance.

Having said that, I'd be keen to learn more about the way data is saved for the production service. Maybe we could chat in our next tech planning meeting?

**Comment by peterdudfield** [comment]
As this is stable now, ill close this for the moment
