### ISSUE TITLE
[Meta] CNN production Improvements

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#86]
Split into smaller issues

# Sun
- filter results depending on sun elevation https://github.com/openclimatefix/nowcasting_forecast/issues/89
- Add sun data to model - https://github.com/openclimatefix/nowcasting_forecast/issues/93 (low priority)

# GSP

1. make read function for GSP from database, to get all the latest yields - https://github.com/openclimatefix/nowcasting_dataset/issues/666
2. add to predict _pv_yiled, this would just be turning on a flag - https://github.com/openclimatefix/nowcasting_forecast/issues/91
3. add gsp id in to model - https://github.com/openclimatefix/nowcasting_forecast/issues/92 (low priority)
4. https://github.com/openclimatefix/nowcasting_forecast/issues/104
5. https://github.com/openclimatefix/nowcasting_infrastructure/issues/97

# BUGS
- Investigate why no forecasts on the night of 17th/18th May - https://github.com/openclimatefix/nowcasting_forecast/issues/88
- Satellite Consumer bug - openclimatefix/Satip#109
- Make sure model is getting the correct NWP data - https://github.com/openclimatefix/nowcasting_forecast/issues/94
- https://github.com/openclimatefix/Satip/issues/112
- https://github.com/openclimatefix/nowcasting_forecast/issues/95
- https://github.com/openclimatefix/nowcasting_forecast/issues/97
- https://github.com/openclimatefix/nowcasting_forecast/issues/101
- https://github.com/openclimatefix/nowcasting_forecast/issues/102
- https://github.com/openclimatefix/nowcasting_forecast/issues/106
- https://github.com/openclimatefix/nowcasting_forecast/issues/114

**Comment by JackKelly** [comment]
In terms of priorities, I'd propose:

1. #93 (with luck, once you give the Sun's elevation (and azimuth?) to the model, then you won't need to bother with #89  :slightly_smiling_face: )
2. #92 (the model _definitely_ needs to know the ID of the GSP it's predicting for! That should help a lot.)
3. #91

**Comment by jacobbieker** [comment]
Yeah, I'd agree with that priority list. I'll work on the Satip bug first to try to make that a bit more reliable and stable, which might also fix #88

**Comment by peterdudfield** [comment]
> In terms of priorities, I'd propose:
> 
> 1. [Add Sun data to model #93](https://github.com/openclimatefix/nowcasting_forecast/issues/93) (with luck, once you give the Sun's elevation (and azimuth?) to the model, then you won't need to bother with [Add Sun filter #89](https://github.com/openclimatefix/nowcasting_forecast/issues/89)  🙂 )
> 2. [GSP ID embedding #92](https://github.com/openclimatefix/nowcasting_forecast/issues/92) (the model _definitely_ needs to know the ID of the GSP it's predicting for! That should help a lot.)
> 3. [Use GSP recent data in model #91](https://github.com/openclimatefix/nowcasting_forecast/issues/91)

I like the Idea of still doing #89 because it will improve/fix other models too

**Comment by jacobbieker** [comment]
I might also add increasing the satellite image input size? Currently, at 24x24 for HRV and non-HRV, its quite a small context area, even just doubling it to 48x48 could be a big help.

**Comment by peterdudfield** [comment]
> I might also add increasing the satellite image input size? Currently, at 24x24 for HRV and non-HRV, its quite a small context area, even just doubling it to 48x48 could be a big help.

This would mean making a new batch, and re training. Perhaps we could put it on the list of things, but might take some time to make new batches

**Comment by jacobbieker** [comment]
> > I might also add increasing the satellite image input size? Currently, at 24x24 for HRV and non-HRV, its quite a small context area, even just doubling it to 48x48 could be a big help.
> 
> This would mean making a new batch, and re training. Perhaps we could put it on the list of things, but might take some time to make new batches
> 
> I'm becoming more convienced that #94 is wrong, and tackling that will help big time

Ah okay, I thought the images were saved larger. Sounds good!

**Comment by peterdudfield** [comment]
Unforetunately i think for v15 they are that small. Maybe the hrv ones are bigger
