### ISSUE TITLE
Add Sun filter

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#89]
Would be good to make sure the forecasts are zero at night

TODO check:
Sun Data Source in nowcasting_dataset only produces one elevation for each t0, independent of the forecast horizon. 

Tasks:
1. Add sun to config mvp 2.
2. Then in model code, perhaps [here](https://github.com/openclimatefix/nowcasting_forecast/blob/main/nowcasting_forecast/models/utils.py#L283). Then it would work for all models

1. Filter the forecasts to be zeros is elevation < X.

# Small Problem
At 04:00 the elevation < 0, but at 05:00 there could be solar generation. Maybe there is a way to filter < -5, which might stop the problem at dawn. 

Other ideas: 
- Calucate sun elevation on the fly, and filter forecasts for this. Here writing a function like this would be good
```
def filter_forecast_on_sun(forecast:ForecastSQL):

     # get location

    # get elevation at all target times

     # zero out if below a certina value

return forecast
```
maybe have to loop over all the forecasts with this function
- adjust SunDataSource, so that values are caluclated for all timesteps, not just t0

**Comment by peterdudfield** [comment]
Thanks @JackKelly, ok, the we should give `pvlib` a try. 

@jacobbieker would you be up for this?

**Comment by jacobbieker** [comment]
Yeah, that sounds good, I can tackle it.

**Comment by JackKelly** [comment]
FWIW, here's how `power_perceiver` computes the Sun's azimuth and elevation for each `t0` timestep of each example in a batch on-the-fly: https://github.com/openclimatefix/power_perceiver/blob/main/power_perceiver/np_batch_processor/sun_position.py#L50

**Comment by JackKelly** [comment]
> Yeah, that sounds good, I can tackle it.

Thanks!

Although, as I propose in [this comment](https://github.com/openclimatefix/nowcasting_forecast/issues/86#issuecomment-1130275408), I'd suggest that you first give the model the Sun's azimuth and elevation. If you're lucky, that will be sufficient, and you won't have to "manually" filter the output of the model by the Sun's elevation :slightly_smiling_face:
