### ISSUE TITLE
Add Sun data to model

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_forecast#93]
Add Sun data to model

- add the sun data to the model
- If the model accuarcy doesnt improve, perhaps dont continue
- train model and save new weights to HF
- update nowcasting_forecast model to use sun data

**Comment by JackKelly** [comment]
I expect you're planning to do this already but, if not, I'd definitely recommend giving the model the Sun's elevation and azimuth, if only so the model can infer the season!

**Comment by peterdudfield** [comment]
yea I think that is already in Sun Data Source

**Comment by peterdudfield** [comment]
https://github.com/openclimatefix/nowcasting_dataset/issues/675 - will need to do this first, so lvie sun data can be made
